# Generated by Django 4.1.1 on 2022-10-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0003_stravadetails_alter_route_user_id_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="stravadetails",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="Elevation",
        ),
        migrations.DeleteModel(
            name="Route",
        ),
        migrations.DeleteModel(
            name="stravaDetails",
        ),
    ]
