# Generated by Django 4.1.1 on 2022-09-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapdata", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="route_text",
            new_name="route_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="user_text",
            new_name="user_name",
        ),
    ]
