# Generated by Django 4.1.1 on 2022-11-17 05:30

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(help_text='date started', null=True)),
                ('created_date', models.DateTimeField(help_text='date added to database', null=True)),
                ('time', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True, help_text='time elapsed', null=True), null=True, size=None)),
                ('latlng', django.contrib.gis.db.models.fields.MultiPointField(blank=True, help_text='latlng position', null=True, srid=4326)),
                ('distance', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='distance from start', null=True), null=True, size=None)),
                ('altitude', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='time elapsed', null=True), null=True, size=None)),
                ('velocity_smooth', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='velocity smooth', null=True), null=True, size=None)),
                ('heartrate', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='heart rate', null=True), null=True, size=None)),
                ('cadence', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='cadence', null=True), null=True, size=None)),
                ('watts', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='watts', null=True), null=True, size=None)),
                ('temp', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='temperature', null=True), null=True, size=None)),
                ('moving', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='moving', null=True), null=True, size=None)),
                ('grade_smooth', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='grade smooth', null=True), null=True, size=None)),
                ('elevation', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='elevation values', null=True), null=True, size=None)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='activity path', null=True, srid=4326)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'activity_id')},
            },
        ),
    ]
