# Generated by Django 4.1.1 on 2022-10-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("getdata", "0002_rename_user_id_route_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="user",
            new_name="user_id",
        ),
    ]
