# Generated by Django 4.1.1 on 2022-10-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("getdata", "0003_rename_user_route_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="user_id",
            new_name="user",
        ),
    ]
