# Generated by Django 4.1.1 on 2022-10-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("getdata", "0005_rename_user_route_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elevation",
            old_name="route",
            new_name="route_id",
        ),
    ]
