# Generated by Django 4.1.1 on 2022-11-08 06:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getdata', '0006_rename_route_elevation_route_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('user_id', 'route_id')},
        ),
    ]
