# Generated by Django 4.1.1 on 2022-11-13 09:19

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('getdata', '0007_alter_route_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='date started')),
                ('created_date', models.DateTimeField(verbose_name='date added to database')),
                ('time', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True, help_text='time elapsed', null=True), size=None)),
                ('latlng', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='latlng position', null=True, srid=4326), size=None)),
                ('distance', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='distance from start', null=True), size=None)),
                ('altitude', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='time elapsed', null=True), size=None)),
                ('velocity_smooth', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='velocity smooth', null=True), size=None)),
                ('heartrate', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='heart rate', null=True), size=None)),
                ('cadence', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='cadence', null=True), size=None)),
                ('watts', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='watts', null=True), size=None)),
                ('temp', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='temperature', null=True), size=None)),
                ('moving', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='moving', null=True), size=None)),
                ('grade_smooth', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='grade smooth', null=True), size=None)),
                ('elevation_sampling_points', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='elevation sampling points', null=True, srid=4326), size=None)),
                ('elevation', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='elevation values', null=True), size=None)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='route', null=True, srid=4326)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'activity_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='route',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Elevation',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
