# Generated by Django 4.1.1 on 2022-11-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0008_activity_alter_route_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_date',
            field=models.DateTimeField(help_text='date added to database', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(help_text='date started', null=True),
        ),
    ]
