# Generated by Django 4.1.1 on 2022-11-13 10:00

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0009_alter_activity_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='altitude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='time elapsed', null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cadence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='cadence', null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='distance from start', null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elevation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='elevation values', null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elevation_sampling_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='elevation sampling points', null=True, srid=4326), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='grade_smooth',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='grade smooth', null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='heartrate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='heart rate', null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='latlng',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='latlng position', null=True, srid=4326), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='moving',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='moving', null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='temp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='temperature', null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True, help_text='time elapsed', null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='velocity_smooth',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='velocity smooth', null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='watts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, help_text='watts', null=True), null=True, size=None),
        ),
    ]
